[package]
name = "paseo-metadata"
version = "0.2.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subxt = { workspace = true }
