[package]
name = "polkadot-indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metadata = { path = "../metadata" }
tokio = { version = "1.28.2", features = ["macros", "rt", "rt-multi-thread"] }
subxt = "0.30.1"
clap = { version = "4.3.19", features = ["derive"] }
hybrid-indexer = "0.1.0"
